library(rslp)
context("Apply Rules")
steprules <- readRDS(system.file("steprules.rds", package = "rslp"))

test_that("Plural Reduction Rules", {
  expect_equivalent(rslp:::apply_rules("bons", name = "Plural", steprules = steprules), "bom")
  expect_equivalent(rslp:::apply_rules("balões", name = "Plural", steprules = steprules), "balão")
  expect_equivalent(rslp:::apply_rules("capitães", name = "Plural", steprules = steprules), "capitão")
  expect_equivalent(rslp:::apply_rules("normais", name = "Plural", steprules = steprules), "normal")
  expect_equivalent(rslp:::apply_rules("amáveis", name = "Plural", steprules = steprules), "amável")
  expect_equivalent(rslp:::apply_rules("lençóis", name = "Plural", steprules = steprules), "lençol")
  expect_equivalent(rslp:::apply_rules("barris", name = "Plural", steprules = steprules), "barril")
  expect_equivalent(rslp:::apply_rules("males", name = "Plural", steprules = steprules), "mal")
  expect_equivalent(rslp:::apply_rules("mares", name = "Plural", steprules = steprules), "mar")
  expect_equivalent(rslp:::apply_rules("casas", name = "Plural", steprules = steprules), "casa")
})

test_that("Feminine Reduction Rules", {
  expect_equivalent(rslp:::apply_rules("chefona", name = "Feminine", steprules = steprules), "chefão")
  expect_equivalent(rslp:::apply_rules("vilã", name = "Feminine", steprules = steprules), "vilão")
  expect_equivalent(rslp:::apply_rules("professora", name = "Feminine", steprules = steprules), "professor")
  expect_equivalent(rslp:::apply_rules("americana", name = "Feminine", steprules = steprules), "americano")
  expect_equivalent(rslp:::apply_rules("chilena", name = "Feminine", steprules = steprules), "chileno")
  expect_equivalent(rslp:::apply_rules("inglesa", name = "Feminine", steprules = steprules), "inglês")
  expect_equivalent(rslp:::apply_rules("famosa", name = "Feminine", steprules = steprules), "famoso")
  expect_equivalent(rslp:::apply_rules("maníaca", name = "Feminine", steprules = steprules), "maníaco")
  expect_equivalent(rslp:::apply_rules("prática", name = "Feminine", steprules = steprules), "prático")
  expect_equivalent(rslp:::apply_rules("mantida", name = "Feminine", steprules = steprules), "mantido")
  expect_equivalent(rslp:::apply_rules("cansada", name = "Feminine", steprules = steprules), "cansado")
  expect_equivalent(rslp:::apply_rules("prima", name = "Feminine", steprules = steprules), "primo")
  expect_equivalent(rslp:::apply_rules("passiva", name = "Feminine", steprules = steprules), "passivo")
  expect_equivalent(rslp:::apply_rules("primeira", name = "Feminine", steprules = steprules), "primeiro")
  expect_equivalent(rslp:::apply_rules("sozinha", name = "Feminine", steprules = steprules), "sozinho")
})

test_that("Adverb Reduction Rule", {
  expect_equivalent(rslp:::apply_rules("felizmente", name = "Adverb", steprules = steprules), "feliz")
})

test_that("Aumentative/Dimunutive Reduction Rules", {
  expect_equivalent(rslp:::apply_rules("cansadíssimo", name = "Augmentative", steprules = steprules), "cansa")
  # expect_equivalent(rslp:::apply_rules("amabilíssimo", name = "Augmentative", steprules = steprules), "ama")
  expect_equivalent(rslp:::apply_rules("fortíssimo", name = "Augmentative", steprules = steprules), "fort")
  expect_equivalent(rslp:::apply_rules("chiquérrimo", name = "Augmentative", steprules = steprules), "chiqu")
  expect_equivalent(rslp:::apply_rules("pezinho", name = "Augmentative", steprules = steprules), "pe")
  expect_equivalent(rslp:::apply_rules("maluquinho", name = "Augmentative", steprules = steprules), "maluc")
  expect_equivalent(rslp:::apply_rules("amiguinho", name = "Augmentative", steprules = steprules), "amig")
  expect_equivalent(rslp:::apply_rules("cansadinho", name = "Augmentative", steprules = steprules), "cans")
  expect_equivalent(rslp:::apply_rules("carrinho", name = "Augmentative", steprules = steprules), "carr")
  expect_equivalent(rslp:::apply_rules("grandalhão", name = "Augmentative", steprules = steprules), "grand")
  expect_equivalent(rslp:::apply_rules("dentuça", name = "Augmentative", steprules = steprules), "dent")
  expect_equivalent(rslp:::apply_rules("mulheraço", name = "Augmentative", steprules = steprules), "mulher")
  expect_equivalent(rslp:::apply_rules("cansadão", name = "Augmentative", steprules = steprules), "cans")
  expect_equivalent(rslp:::apply_rules("corpázio", name = "Augmentative", steprules = steprules), "corp")
  expect_equivalent(rslp:::apply_rules("pratarraz", name = "Augmentative", steprules = steprules), "prat")
  expect_equivalent(rslp:::apply_rules("bocarra", name = "Augmentative", steprules = steprules), "boc")
  expect_equivalent(rslp:::apply_rules("calorzão", name = "Augmentative", steprules = steprules), "calor")
  expect_equivalent(rslp:::apply_rules("meninão", name = "Augmentative", steprules = steprules), "menin")
})
