library(rslp)
context("rslp")
steprules <- readRDS(system.file("steprules.rds", package = "rslp"))

test_that("rslp works fine", {
  expect_equal(rslp::rslp("bons"), "bom")
  expect_equal(rslp::rslp("bal\u00f5es"), "bal")
  expect_equal(rslp::rslp("capit\u00e3es"), "capita")
  expect_equal(rslp::rslp("normais"), "norm")
  expect_equal(rslp::rslp("am\u00e1veis"), "am")
  expect_equal(rslp::rslp("len\u00e7\u00f3is"), "lencol")
  expect_equal(rslp::rslp("barris"), "barril")
  expect_equal(rslp::rslp("males"), "mal")
  expect_equal(rslp::rslp("mares"), "mar")
  expect_equal(rslp::rslp("casas"), "cas")
  expect_equal(rslp::rslp("chefona"), "chef")
  expect_equal(rslp::rslp("vil\u00e3"), "vila")
  expect_equal(rslp::rslp("professora"), "profes")
  expect_equal(rslp::rslp("americana"), "americ")
  expect_equal(rslp::rslp("chilena"), "chilen")
  expect_equal(rslp::rslp("inglesa"), "ingl")
  expect_equal(rslp::rslp("famosa"), "fam")
  expect_equal(rslp::rslp("man\u00edaca"), "man")
  expect_equal(rslp::rslp("pr\u00e1tica"), "prat")
  expect_equal(rslp::rslp("mantida"), "mant")
  expect_equal(rslp::rslp("cansada"), "cans")
  expect_equal(rslp::rslp("prima"), "prim")
  expect_equal(rslp::rslp("passiva"), "passiv")
  expect_equal(rslp::rslp("primeira"), "prim")
  expect_equal(rslp::rslp("sozinha"), "so")
  expect_equal(rslp::rslp("felizmente"), "feliz")
  expect_equal(rslp::rslp("cansad\u00edssimo"), "cans")
  # expect_equal(rslp::rslp("amabil\u00edssimo"), "ama")
  expect_equal(rslp::rslp("fort\u00edssimo"), "fort")
  expect_equal(rslp::rslp("chiqu\u00e9rrimo"), "chiqu")
  expect_equal(rslp::rslp("pezinho"), "pe")
  expect_equal(rslp::rslp("maluquinho"), "maluc")
  expect_equal(rslp::rslp("amiguinho"), "amig")
  expect_equal(rslp::rslp("cansadinho"), "cans")
  expect_equal(rslp::rslp("carrinho"), "carr")
  expect_equal(rslp::rslp("grandalh\u00e3o"), "grand")
  #expect_equal(rslp::rslp("dentu\u00e7a"), "dent") # ver pq não funciona
  expect_equal(rslp::rslp("mulhera\u00e7o"), "mulh")
  expect_equal(rslp::rslp("cansad\u00e3o"), "cans")
  expect_equal(rslp::rslp("corp\u00e1zio"), "corp")
  expect_equal(rslp::rslp("pratarraz"), "prat")
  #expect_equal(rslp::rslp("bocarra"), "boc") # ver pq não funciona
  expect_equal(rslp::rslp("calorz\u00e3o"), "cal")
  expect_equal(rslp::rslp("menin\u00e3o"), "menin")
})
